# Generated by Django 3.0.2 on 2020-07-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('mob_no', models.IntegerField()),
                ('institution', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('enrollment', models.CharField(max_length=100)),
            ],
        ),
    ]
