# Generated by Django 3.0.2 on 2020-07-11 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_workshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='link',
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_type', models.CharField(max_length=100)),
                ('enrolled_for', models.CharField(max_length=100)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.User')),
            ],
        ),
    ]
