# Generated by Django 3.0.2 on 2020-07-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_auto_20200711_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming_events',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_desc', models.CharField(max_length=500)),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.IntegerField()),
                ('event_month', models.CharField(max_length=100)),
                ('event_image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
