# Generated by Django 3.0.6 on 2020-07-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_upcoming_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offline',
            fields=[
                ('off_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Offdesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('career', models.CharField(max_length=100)),
                ('syllabus', models.CharField(max_length=100)),
                ('scope', models.CharField(max_length=100)),
                ('off_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.Offline')),
            ],
        ),
    ]
