# Generated by Django 3.0.6 on 2020-07-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0005_offdesc_offline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offdesc',
            name='career',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='offdesc',
            name='course',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='offdesc',
            name='scope',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='offdesc',
            name='syllabus',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='offline',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
