# Generated by Django 3.0.6 on 2020-07-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0006_auto_20200715_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offdesc',
            name='career',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='offdesc',
            name='course',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='offdesc',
            name='scope',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='offdesc',
            name='syllabus',
            field=models.CharField(max_length=500),
        ),
    ]
