# Generated by Django 3.0.6 on 2020-07-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0007_auto_20200715_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_title', models.CharField(max_length=500)),
                ('c_description', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.Offline')),
            ],
        ),
    ]
