# Generated by Django 3.0.6 on 2020-07-15 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0008_branch_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institutes',
            fields=[
                ('insti_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('course', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='online',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.Branch'),
        ),
    ]
