# Generated by Django 3.0.6 on 2020-07-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0010_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online',
            name='image',
        ),
        migrations.AddField(
            model_name='online',
            name='intro_video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
