# Generated by Django 3.0.6 on 2020-07-17 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0012_auto_20200716_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offline',
            new_name='Offline_course',
        ),
        migrations.RenameModel(
            old_name='Offdesc',
            new_name='Offline_description',
        ),
        migrations.RenameModel(
            old_name='Branch',
            new_name='Online_branch',
        ),
        migrations.RenameModel(
            old_name='Online',
            new_name='Online_course',
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='Online_course_video',
        ),
    ]
