# Generated by Django 3.0.6 on 2020-07-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0013_auto_20200717_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('mentorship_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title1', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
