# Generated by Django 3.0.8 on 2020-07-28 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0017_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.CreateModel(
            name='Newsletter_videos1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('videos1', models.FileField(upload_to='videos1/')),
                ('newsletter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.Newsletter')),
            ],
        ),
    ]
