# Generated by Django 3.0.8 on 2020-07-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0018_auto_20200728_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='videos1',
            field=models.FileField(blank=True, upload_to='videos1/'),
        ),
    ]
